blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from . import views

app_name = 'blog'


urlpatterns = [
     path('',
          cache_page(60*30)
          (views.PodcastListView.as_view()),
          name='podcast_list'),
     path('episodes/',
          views.EpisodeListView.as_view(),
          name='episode_list'),
     path('<slug:slug>/',
          cache_page(60*30)
          (views.PodcastEpisodesDetailView.as_view()),
          name='podcast_detail'),
     path('<slug:podcast_slug>/episodes/<slug:episode_slug>/',
          cache_page(60*30)
          (views.EpisodeDetailView.as_view()),
          name='episode_detail'),
]

cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'


urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<slug:product_slug>/', views.cart_add, name='cart_add'),
    path('remove/<slug:product_slug>/', views.cart_remove, name='cart_remove'),
]

coupons/urls.py
from django.urls import path

from .views import coupon_apply

app_name = 'coupons'

urlpatterns = [
    path('apply/', coupon_apply, name='apply'),
]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'


urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('admin/order/<int:order_id>/',
         views.admin_order_detail,
         name='admin_order_detail'),
    path('admin/order/<int:order_id>/pdf/',
         views.admin_order_pdf,
         name='admin_order_pdf'),
]

podcast/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

# from rest_framework.documentation import include_docs_urls
# from rest_framework.schemas import get_schema_view

from users import views as user_views

# API_TITLE = 'Podcast API via CoreAPI'
# API_DESCRIPTION = 'Description'
# schema_view = get_schema_view(title='Podcast API')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/',
         auth_views.LoginView.as_view(template_name='users/login.html/'),
         name='login'
         ),
    path('logout/',
         auth_views.LogoutView.as_view(template_name='users/logout.html/'),
         name='logout'
         ),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='users/password_reset.html/'),
         name='password_reset'
         ),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html/'),
         name='password_reset_done'
         ),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html/'),
         name='password_reset_confirm'
         ),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html/'),
         name='password_reset_complete'
         ),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('coupons', include('coupons.urls', namespace='coupons')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('shop/', include('shop.urls', namespace='shop')),
    path('orders/', include('orders.urls', namespace='orders')),
    #     path('silk/', include('silk.urls', namespace='silk')),
#     path('api/v1/', include('api.urls')),
#     path('api-auth/', include('rest_framework.urls')),
#     path('api/v1/rest-auth/', include('rest_auth.urls')),
#     path('api/v1/rest-auth/registration/',  # new
     #     include('rest_auth.registration.urls')),
#     path('docs/', include_docs_urls(title=API_TITLE,
                                   #  description=API_DESCRIPTION)),
#     path('schema/', schema_view),
    path('', include('blog.urls', namespace='podcast')),
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'


urlpatterns = [
    path('', views.ProductListView.as_view(), name='product_list'),
    path('<slug:slug>', views.product_detail, name='product_detail'),
]

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 6)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
        choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST

from shop.models import Product
from coupons.forms import CouponApplyForm

from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_slug):
    cart = Cart(request)
    product = get_object_or_404(Product, slug=product_slug)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_slug):
    cart = Cart(request)
    product = get_object_or_404(Product, slug=product_slug)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
            initial={'quantity': item['quantity'],
                     'update': True}
        )
    coupon_apply_form = CouponApplyForm()
    context = {'cart': cart, 'coupon_apply_form': coupon_apply_form}
    return render(request, 'cart/detail.html', context)

cart/templates/cart/detail.html
{% extends "basic.html" %}
{% load static %}

{% block title %}Your shopping cart{% endblock %}

{% block content %}
<h1>Your shopping cart</h1>
<h2>{{ product.name }}</h2>
<table class="cart">
    <thead>
        <tr>
            <th>Image</th>
            <th>Product</th>
            <th>Quantity</th>
            <th>Remove</th>
            <th>Unit Price}</th>
            <th>Price</th>
        </tr>
    </thead>
    <tbody>
        {% for item in cart %}
            {% with product=item.product %}
            <tr>
                <td>
                    <a href="{{ product.get_absolute_url }}">
                        <img src="{% if product.image %}{{ product.image.url }}
                        {% else %}{% static 'media/no-image.png' %}{% endif %}">
                    </a>
                </td>
                <td>{{ product.name }}</td>
                <td>
                    <form action="{% url 'cart:cart_add' product.slug %}" method="post">
                        {{ item.update_quantity_form.quantity }}
                        {{ item.update_quantity_form.update }}
                        <input type="submit" value="Update">
                        {% csrf_token %}
                    </form>
                </td>
                <td><a href="{% url 'cart:cart_remove' product.slug %}">Remove</a></td>
                <td class="num">${{ item.price }}</td>
                <td class="num">${{ item.total_price }}</td>
            </tr>
            {% endwith %}
        {% endfor %}
        {% if cart.coupon %}
        <tr class="subtotal">
            <td>Subtotal</td>
            <td colspan="4"></td>
            <td class="num">${{ cart.get_total_price|floatformat:"2" }}</td>
        </tr>
        <tr>
            <td>
                "{{ cart.coupon.code }}" coupon
                ({{ cart.coupon.discount }}% off)
            </td>
            <td colspan="4"></td>
            <td class="num neg">
                - ${{ cart.get_discount|floatformat:"2" }}
            </td>
        </tr>
      {% endif %}
      <tr class="total">
        <td>Total</td>
        <td colspan="4"></td>
        <td class="num">
            ${{ cart.get_total_price_after_discount|floatformat:"2" }}
        </td>
    </tr>
    </tbody>
</table>
<p>Apply a coupon:</p>
<form action="{% url 'coupons:apply' %}" method="post">
    {{ coupon_apply_form }}
    <input type="submit" value="Apply">
    {% csrf_token %}
</form>
<p class="text-right">
    <a href="{% url 'shop:product_list' %}" class="btn btn-info">Continue shopping</a>
    <a href="{% url 'orders:order_create' %}" class="btn btn-success">Checkout</a>
</p>
{% endblock %}