blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from . import views

app_name = 'blog'


urlpatterns = [
     path('',
          cache_page(60*30)
          (views.PodcastListView.as_view()),
          name='podcast_list'),
     path('episodes/',
          views.EpisodeListView.as_view(),
          name='episode_list'),
     path('<slug:slug>/',
          cache_page(60*30)
          (views.PodcastEpisodesDetailView.as_view()),
          name='podcast_detail'),
     path('<slug:podcast_slug>/episodes/<slug:episode_slug>/',
          cache_page(60*30)
          (views.EpisodeDetailView.as_view()),
          name='episode_detail'),
]

cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'


urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<slug:product_slug>/', views.cart_add, name='cart_add'),
    path('remove/<slug:product_slug>/', views.cart_remove, name='cart_remove'),
]

podcast/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

# from rest_framework.documentation import include_docs_urls
# from rest_framework.schemas import get_schema_view

from users import views as user_views

# API_TITLE = 'Podcast API via CoreAPI'
# API_DESCRIPTION = 'Description'
# schema_view = get_schema_view(title='Podcast API')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/',
         auth_views.LoginView.as_view(template_name='users/login.html/'),
         name='login'
         ),
    path('logout/',
         auth_views.LogoutView.as_view(template_name='users/logout.html/'),
         name='logout'
         ),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='users/password_reset.html/'),
         name='password_reset'
         ),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html/'),
         name='password_reset_done'
         ),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html/'),
         name='password_reset_confirm'
         ),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html/'),
         name='password_reset_complete'
         ),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('coupons', include('coupons.urls', namespace='coupons')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('shop/', include('shop.urls', namespace='shop')),
    path('orders/', include('orders.urls', namespace='orders')),
    #     path('silk/', include('silk.urls', namespace='silk')),
#     path('api/v1/', include('api.urls')),
#     path('api-auth/', include('rest_framework.urls')),
#     path('api/v1/rest-auth/', include('rest_auth.urls')),
#     path('api/v1/rest-auth/registration/',  # new
     #     include('rest_auth.registration.urls')),
#     path('docs/', include_docs_urls(title=API_TITLE,
                                   #  description=API_DESCRIPTION)),
#     path('schema/', schema_view),
    path('', include('blog.urls', namespace='podcast')),
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'


urlpatterns = [
    path('', views.ProductListView.as_view(), name='product_list'),
    path('<slug:slug>', views.product_detail, name='product_detail'),
]

shop/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.db.models.signals import post_save
from PIL import Image


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status='published')


class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, unique=True)
    image = models.ImageField(
        upload_to='category-images', null=True, blank=True)

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category',
                       kwargs={'slug': self.slug})

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        img = Image.open(self.image.path)

        if img.height > 300 and img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)


class Product(models.Model):
    category = models.ForeignKey(
        Category, related_name='products',
        on_delete=models.CASCADE)
    name = models.CharField(max_length=150)
    slug = models.SlugField(max_length=100, unique=True)
    price = models.DecimalField(
        max_digits=10, decimal_places=2, default=0)
    description = models.TextField()
    short_description = models.TextField(null=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    publish = models.DateTimeField(default=timezone.now)
    # As the main image 
    image = models.ImageField(upload_to='products/%Y/%m/%d',
                              blank=True, default='no-image.jpg')
    # objects = models.Manager()  # Default manager
    # published = PublishedManager()  # New manager

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail',
                       kwargs={'slug': self.slug})
        
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        img = Image.open(self.image.path)

        if img.height > 300 and img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)


class ProductImage(models.Model):
    # Other images for a product
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, blank=True, null=True, default=None,
        related_name='product_image')
    image = models.ImageField(
        upload_to='product-images/%Y/%m/%d', default='no-image.jpg')
    is_active = models.BooleanField(default=True)
    is_main = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.product.name

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        img = Image.open(self.image.path)

        if img.height > 300 and img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

"""
# Or use choices?
class Status(models.Model):
    name = models.CharField(max_length=24, blank=True, null=True, default=None)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'Status {self.name}'

    class Meta:
        verbose_name = 'Status'
        verbose_name_plural = 'Statuses'

class Order(models.Model):
    # total price for all products in order
    total_price = models.DecimalField(
        max_digits=10, decimal_places=2, default=0)
    customer_name = models.CharField(max_length=55)
    customer_email = models.EmailField(blank=True, null=True, default=None)
    customer_phone = models.CharField(
        max_length=48, blank=True, null=True, default=None)
    customer_address = models.CharField(max_length=120, null=True)
    comments = models.TextField(blank=True, null=True, default=None)
    status = models.ForeignKey(Status, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'Order № {self.id}, {self.status.name}'

    def save(self, *args, **kwargs):
        return super(Order, self).save(*args, **kwargs)


class ProductInOrder(models.Model):
    order = models.ForeignKey(
        Order, on_delete=models.CASCADE, blank=True, null=True, default=None)
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, blank=True, null=True, default=None)
    created = models.DateTimeField(auto_now_add=True)
    quantity = models.IntegerField(default=1)
    # Best way?
    price_per_item = models.DecimalField(
        max_digits=10, decimal_places=2, default=0)
    total_price = models.DecimalField(
        max_digits=10, decimal_places=2, default=0)  # price*quantity

    updated = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return f'{self.product.name}'

    def save(self, *args, **kwargs):
        price_per_item = self.product.price
        self.price_per_item = price_per_item
        print(self.quantity)

        self.total_price = int(self.quantity) * price_per_item

        return super(ProductInOrder, self).save(*args, **kwargs)


def product_in_order_post_save(sender, instance, created, **kwargs):
    order = instance.order
    all_products_in_order = ProductInOrder.objects.filter(
        order=order, is_active=True)

    order_total_price = 0
    for item in all_products_in_order:
        order_total_price += item.total_price

    instance.order.total_price = order_total_price
    instance.order.save(force_update=True)


post_save.connect(product_in_order_post_save, sender=ProductInOrder)
"""

shop/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import DetailView, ListView
from cart.forms import CartAddProductForm
from .models import Product, Category


class ProductListView(ListView):
    model = Product
    form = CartAddProductForm()

    # paginate_by = 10

    # A simple expample of get_context_data.
    # In template use {{ page_title }} and it returns text 'Author'
    # def get_context_data(self, **kwargs):
    #     data = super().get_context_data(**kwargs)
    #     data['page_title'] = 'Authors'
    #     return data



def product_detail(request, slug):
    product = get_object_or_404(Product,
                                slug=slug,
                                is_active=True)
    cart_product_form = CartAddProductForm()

    return render(request,
                  'shop/product_detail.html',
                  {'product': product,
                   'cart_product_form': cart_product_form})

shop/templates/basic.html
{% load static shop_tags thumbnail %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>{% block title %}Shop{% endblock title %}</title>

    <!-- Bootstrap -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <!--/ Style-CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">

    <!-- /Fonts -->
    <link href="//fonts.googleapis.com/css?family=Lato:100,100i,300,300i,500,500i,700" rel="stylesheet">
    <link href="//fonts.googleapis.com/css?family=Source+Sans+Pro:200,200i,400,400i,600,600i," rel="stylesheet">
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="/">Empire</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample07"
                    aria-controls="navbarsExample07" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarsExample07">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="/episodes/">All episodes</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'shop:product_list' %}">Shop</a>
                        </li>
                        <!-- <li class="nav-item">
                            <a class="nav-link disabled" href="#">Disabled</a>
                        </li> -->

                        <!-- Categories -->
                        <li class="nav-item dropdown active">
                            <a class="nav-link dropdown-toggle" href="https://example.com" id="dropdown07"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Categories</a>
                            <div class="dropdown-menu" aria-labelledby="dropdown07">
                                {% get_categories as categories %}
                                {% for category in categories %}
                                    <a class="dropdown-item" href="/"><img class="square article-img" src="{{ category.image.url }}" alt="{{ category.name }}">{{ category.name }}</a>
                                {% endfor %}
                            </div>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link" href="https://twitter.com/classical_music">Statistics</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-item nav-link" href="https://t.me/kant1742">Contact us</a>
                        </li>
                    </ul>
                    <div class="navbar-nav">
                        {% comment %}
                            {% if user.is_authenticated %}
                                <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>
                                <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
                            {% else %}
                                <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                                <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
                            {% endif %}
                        {% endcomment %}
                        
                    </div>
                    <form class="form-inline my-2 my-md-0">
                        <input class="form-control" type="text" placeholder="Search" aria-label="Search">
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <main role="main" class="container">
        <div class="row">
            <div class="col-md-12">
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-{{ message.tags }}">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
                <div id="subheader">
                    <div class="cart">
                        {% with total_items=cart|length %}
                            {% if cart|length > 0 %}
                                Your cart:
                                <a href="{% url 'cart:cart_detail' %}">
                                    {{ total_items }} item{{ total_items|pluralize }},
                                    ${{ cart.get_total_price }}
                                </a>
                            {% else %}
                                Your cart is empty.
                            {% endif %}
                        {% endwith %}
                    </div>
                </div>
                {% block content %}{% endblock %}
            </div>
        </div>
    </main>

    <footer class="section footer-classic context-dark bg-image" style="background: rgb(33, 37, 41);">
        <div class="container">
            <div class="row row-30">
                <div class="col-md-4 col-xl-5">
                    <div class="pr-xl-4"><a class="brand" href="index.html"><img class="brand-logo-light"
                                src="images/agency/logo-inverse-140x37.png" alt="" width="140" height="37"
                                srcset="images/agency/logo-retina-inverse-280x74.png 2x"></a>
                        <p>All my podcasts.</p>
                        <!-- Rights-->
                        <p class="rights">© 2020 Empire. All rights aren't reserved.</p>
                    </div>
                </div>
                <div class="col-md-4">
                    <h5>Contacts</h5>
                    <dl class="contact-list">
                        <dt>Email:</dt>
                        <dd><a href="mailto:qazwsxedc19909@gmail.com">qazwsxedc19909@gmail.com</a></dd>
                    </dl>
                </div>
                <div class="col-md-4 col-xl-3">
                    <h5>Links</h5>
                    <ul class="nav-list">
                        <li><a href="#">About</a></li>
                        <li><a href="#">Projects</a></li>
                        <li><a href="#">Blog</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"> </script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"> </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script> 
</body>

</html>